export const SPECIES = {
  oak: {
    name: 'English Oak',
    nameDE: 'Stieleiche',
    rootTypeLabel: 'deep taproot',
    emoji: '🌰',
    g: 0.65,      // Gravity strength (deep)
    bp: 0.07,     // Branch probability (slow)
    la: 0.55,     // Lateral angle
    ss: 0.12,     // Step size
    mbd: 3,       // Max branch depth
    initialTips: 6,
    rootRadiusBase: 0.035,
    lateralReach: 5.0,
    maxDepth: 4.5,
    waterSensitivity: 0.85,
    nutrientSensitivity: 0.75,
  },
  cherry: {
    name: 'Wild Cherry',
    nameDE: 'Vogelkirsche',
    rootTypeLabel: 'heart roots',
    emoji: '🌸',
    g: 0.38,
    bp: 0.12,
    la: 0.95,
    ss: 0.15,
    mbd: 4,
    initialTips: 8,
    rootRadiusBase: 0.024,
    lateralReach: 6.0,
    maxDepth: 2.8,
    waterSensitivity: 0.65,
    nutrientSensitivity: 0.55,
  },
  birch: {
    name: 'Birch',
    nameDE: 'Birke',
    rootTypeLabel: 'fine dense',
    emoji: '🌿',
    g: 0.22,
    bp: 0.18,
    la: 0.85,
    ss: 0.18,
    mbd: 5,
    initialTips: 12,
    rootRadiusBase: 0.018,
    lateralReach: 8.0,
    maxDepth: 1.8,
    waterSensitivity: 0.95,
    nutrientSensitivity: 0.92,
  },
  pine: {
    name: 'Pine',
    nameDE: 'Kiefer',
    rootTypeLabel: 'sinker roots',
    emoji: '🌲',
    g: 0.55,
    bp: 0.08,
    la: 0.65,
    ss: 0.14,
    mbd: 3,
    initialTips: 5,
    rootRadiusBase: 0.030,
    lateralReach: 4.5,
    maxDepth: 3.5,
    waterSensitivity: 0.82,
    nutrientSensitivity: 0.85,
  },
  spruce: {
    name: 'Spruce',
    nameDE: 'Fichte',
    rootTypeLabel: 'flat plate',
    emoji: '🎄',
    g: 0.15,
    bp: 0.22,
    la: 1.15,
    ss: 0.20,
    mbd: 6,
    initialTips: 16,
    rootRadiusBase: 0.015,
    lateralReach: 10.0,
    maxDepth: 1.2,
    waterSensitivity: 0.98,
    nutrientSensitivity: 0.95,
  },
  acer: {
    name: 'Maple',
    nameDE: 'Ahorn',
    rootTypeLabel: 'intermediate',
    emoji: '🍁',
    g: 0.42,
    bp: 0.11,
    la: 0.78,
    ss: 0.16,
    mbd: 4,
    initialTips: 7,
    rootRadiusBase: 0.025,
    lateralReach: 5.5,
    maxDepth: 3.0,
    waterSensitivity: 0.78,
    nutrientSensitivity: 0.82,
  },
  tilia: {
    name: 'Linden',
    nameDE: 'Linde',
    rootTypeLabel: 'heart roots',
    emoji: '🌼',
    g: 0.35,
    bp: 0.10,
    la: 0.88,
    ss: 0.15,
    mbd: 4,
    initialTips: 8,
    rootRadiusBase: 0.028,
    lateralReach: 6.5,
    maxDepth: 3.2,
    waterSensitivity: 0.80,
    nutrientSensitivity: 0.82,
  },
  platanus: {
    name: 'Plane',
    nameDE: 'Platane',
    rootTypeLabel: 'extensive',
    emoji: '🌳',
    g: 0.48,
    bp: 0.14,
    la: 0.82,
    ss: 0.18,
    mbd: 3,
    initialTips: 6,
    rootRadiusBase: 0.032,
    lateralReach: 8.5,
    maxDepth: 3.8,
    waterSensitivity: 0.85,
    nutrientSensitivity: 0.90,
  }
};

export const SPECIES_ORDER = ['oak', 'cherry', 'birch', 'pine', 'spruce', 'acer', 'tilia', 'platanus'];

export const SOIL_TYPES = {
  sand: {
    color: '#c2b280',
    waterDiffusion: 0.25,
    baselineMoisture: 0.35,
    drainage: 0.85,
    porosity: 0.42,
  },
  loam: {
    color: '#8b4513',
    waterDiffusion: 0.15,
    baselineMoisture: 0.65,
    drainage: 0.45,
    porosity: 0.38,
  },
  clay: {
    color: '#4a3728',
    waterDiffusion: 0.05,
    baselineMoisture: 0.85,
    drainage: 0.15,
    porosity: 0.24,
  },
  silt: {
    color: '#a0522d',
    waterDiffusion: 0.12,
    baselineMoisture: 0.55,
    drainage: 0.55,
    porosity: 0.32,
  }
};
